### ISSUE TITLE
questions about c.eavl_ckpt

### ISSUE THREAD

**Issue by qinliuru** [cool-xuan/msflow#3]
Testing:

   if c.mode == 'test':
        start_epoch = load_weights(parallel_flows, fusion_flow, c.eavl_ckpt)

I can't find where the c.eavl_ckpt is, I tried using the path to the training weights file, but it didn't feel right.

**Comment by sunchengyi** [comment]
c.eval_ckpt is one of the arguments parsed by main.py.
Yet, if you use the testing command line and even set c.eval_ckpt correctly,
I think, it would not work: load_weights() needs another argument, "file_name".

However, even you add "file_name" by hand, it would not work as you expect,
since, the model would be trained for c.sub_epochs times before testing.

You could set c.sub_epochs = 0. And then the model would not be trained.
But in this case, all of the model files would be rewritten by the current model after testing.

So, I think you should implement the test function yourself.

**Comment by cool-xuan** [comment]
@qinliuru 'eavl_ckpt' is a typo, which should be 'eval_ckpt', referring to the checkpoint path of the trained model.

And as commented by @sunchengyi, there are undefined and unnecessary args 'ckpt_dir' and 'file_name' in load_weights(). We have utilized 'ckpt_ckpt' to replace these args for loading trained weights. 

The code for testing is updated in  [91e37c8](https://github.com/cool-xuan/msflow/commit/91e37c88b97ca20e736b283161d56563e3f510b6).

**Comment by sunchengyi** [comment]
@cool-xuan 
I think the calling load_weights() in the resume branch in "train()" should be modified, too.

**Comment by cool-xuan** [comment]
> @qinliuru I think the calling load_weights() in the resume branch in "train()" should be modified, too.

As you recommend, [0a4f5fe](https://github.com/cool-xuan/msflow/commit/0a4f5fe8844df06b8c942da3d7b37847dfa6d268) has updated this bug.
